# Generated by Django 6.0.3 on 2026-05-06 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('archivo', models.BinaryField(blank=True, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('aprendiz', models.ForeignKey(blank=True, db_column='aprendiz_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables', to='academic.aprendiz')),
                ('trimestre', models.ForeignKey(db_column='trimestre_id', on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='academic.trimestre')),
            ],
            options={
                'db_table': 'entregable',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('aprendiz', models.ForeignKey(blank=True, db_column='aprendiz_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='academic.aprendiz')),
                ('entregable', models.ForeignKey(db_column='entregable_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='projects.entregable')),
                ('evaluador', models.ForeignKey(db_column='evaluador_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to='academic.instructor')),
                ('gaes', models.ForeignKey(blank=True, db_column='gaes_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='academic.gaes')),
            ],
            options={
                'db_table': 'evaluacion',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20)),
                ('gaes', models.ForeignKey(db_column='gaes_id', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='academic.gaes')),
            ],
            options={
                'db_table': 'proyecto',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='entregable',
            name='proyecto',
            field=models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='projects.proyecto'),
        ),
        migrations.CreateModel(
            name='ProyectoEntregable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregable', models.ForeignKey(db_column='entregable_id', on_delete=django.db.models.deletion.CASCADE, to='projects.entregable')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
            options={
                'db_table': 'proyecto_entregable',
                'ordering': ['id'],
            },
        ),
    ]
