# Generated by Django 6.0.3 on 2026-06-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_entregable_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='escala_calificacion',
            field=models.CharField(choices=[('5', '1 a 5'), ('10', '1 a 10'), ('100', '1 a 100')], default='100', max_length=3),
        ),
    ]
