# Generated by Django 6.0.3 on 2026-05-06 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ficha', models.CharField(max_length=20, unique=True)),
                ('programa_formacion', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('tecnico', 'Tecnico'), ('tecnologo', 'Tecnologo')], default='tecnico', max_length=20)),
                ('jornada', models.CharField(choices=[('mañana', 'Manana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('mixta', 'Mixta')], max_length=20)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
            ],
            options={
                'db_table': 'ficha',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='aprendiz_perfiles', to='accounts.usuario')),
                ('ficha', models.ForeignKey(db_column='ficha_id', on_delete=django.db.models.deletion.CASCADE, related_name='aprendices', to='academic.ficha')),
            ],
            options={
                'db_table': 'aprendiz',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gaes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ficha', models.ForeignKey(db_column='ficha_id', on_delete=django.db.models.deletion.CASCADE, related_name='gaes', to='academic.ficha')),
            ],
            options={
                'db_table': 'gaes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AprendizGaes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprendiz', models.ForeignKey(db_column='aprendiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='gaes_links', to='academic.aprendiz')),
                ('gaes', models.ForeignKey(db_column='gaes_id', on_delete=django.db.models.deletion.CASCADE, related_name='aprendiz_links', to='academic.gaes')),
            ],
            options={
                'db_table': 'aprendiz_gaes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('ficha', models.ForeignKey(blank=True, db_column='ficha_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructores', to='academic.ficha')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='instructor_perfiles', to='accounts.usuario')),
            ],
            options={
                'db_table': 'instructor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('pendiente', 'Pendiente')], default='activo', max_length=20)),
                ('ficha', models.ForeignKey(db_column='ficha_id', on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='academic.ficha')),
            ],
            options={
                'db_table': 'trimestre',
                'ordering': ['ficha_id', 'numero'],
            },
        ),
    ]
