# Generated by Django 6.0.3 on 2026-06-01 03:04

import calendar
from datetime import date, timedelta

from django.db import migrations


def _add_months(value, months):
    month_index = value.month - 1 + months
    year = value.year + month_index // 12
    month = month_index % 12 + 1
    day = min(value.day, calendar.monthrange(year, month)[1])
    return date(year, month, day)


def completar_trimestres(apps, schema_editor):
    Ficha = apps.get_model('academic', 'Ficha')
    Trimestre = apps.get_model('academic', 'Trimestre')
    hoy = date.today()

    for ficha in Ficha.objects.all():
        total = 7 if ficha.nivel == 'tecnologo' else 4
        for numero in range(1, total + 1):
            fecha_inicio = _add_months(ficha.fecha_inicio, (numero - 1) * 3)
            fecha_fin = _add_months(fecha_inicio, 3) - timedelta(days=1)
            if fecha_fin < hoy:
                estado = 'finalizado'
            elif fecha_inicio > hoy:
                estado = 'pendiente'
            else:
                estado = 'activo'
            Trimestre.objects.get_or_create(
                ficha_id=ficha.id,
                numero=numero,
                defaults={
                    'fecha_inicio': fecha_inicio,
                    'fecha_fin': fecha_fin,
                    'estado': estado,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_instructor_trimestre'),
    ]

    operations = [
        migrations.RunPython(completar_trimestres, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='trimestre',
            unique_together={('ficha', 'numero')},
        ),
    ]
