# Generated by Codex on 2026-06-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_trimestre_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='ficha',
            field=models.ForeignKey(
                blank=True,
                db_column='ficha_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='aprendices',
                to='academic.ficha',
            ),
        ),
    ]
