# Generated by Django 6.0.3 on 2026-05-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('url_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('info', 'Info'), ('exito', 'Exito'), ('alerta', 'Alerta')], default='info', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='accounts.usuario')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-creada_en', '-id'],
            },
        ),
    ]
