# Generated by Django 6.0.3 on 2026-05-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_align_legacy_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
